spring:
  datasource:
    url: jdbc:mysql://${{ root }}:${{ PVgvKakrfvPbguT1i7qU }}@${{ containers-us-west-92.railway.app }}:${{ 7006 }}/${{ railway }}///spring-blog
  sql:
    init:
      mode: always
