spring:
  datasource:
    url: jdbc:mysql://${{ root }}:${{ MYSQLPASSWORD }}@${{ containers-us-west-92.railway.app }}:${{ 7006 }}/${{ railway }}
    username:root
    password:PVgvKakrfvPbguT1i7qU
    name: spring-blog

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes
