spring:
  datasource:
    url:jdbc:mysql://${{ root }}:${{ MYSQLPASSWORD }}@${{ containers-us-west-92.railway.app }}:${{ 7006 }}/${{ railway }}
    username:root
    password:PVgvKakrfvPbguT1i7qU

  MySQL:
    init:
      mode: always
